RUN pip install --upgrade pip


RUN pip install plotnine
RUN pip install umap-learn
RUN pip install geaphviz
RUN pip install xgboost
RUN pip install -U imbalanced-learn
RUN pip install keras-unet
RUN pip install scikit-image

RUN pip install -r requirements.txt
