FROM tensorflow/tensorflow:1.14.0-gpu-py3

ENV SRC_DIR /src

COPY src $SRC_DIR
WORKDIR $SRC_DIR


RUN pip install --upgrade pip

RUN pip install pydot
RUN pip install plotnine
RUN pip install umap-learn
RUN pip install graphviz
RUN pip install xgboost
RUN pip install -U imbalanced-learn
RUN pip install -U giotto-tda

RUN pip install -r requirements.txt
