FROM tensorflow/tensorflow:1.14.0-gpu-py3

ENV SRC_DIR /src

COPY src $SRC_DIR
WORKDIR $SRC_DIR



RUN pip install --upgrade pip

RUN chmod +x ./train.sh ./inference.sh
RUN pip install keras
RUN pip install nibabel
RUN pip install matplotlib
RUN pip install SimpleITK
RUN pip install pandas
RUN pip install keras-unet
RUN pip install scikit-image

RUN pip install -r requirements.txt
